version: '1.0'
name: pipeline-202201120
displayName: playground
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-20cbbf31
    displayName: 打包文件
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - npm install -g pnpm && pnpm i && pnpm run build
        artifacts:
          - name: DOCS
            path:
              - ./dist
        caches:
          - ./.pnpm-store
          - ./.npm
        strategy:
          retry: '0'
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID: aliyun
        deployArtifact:
          - source: build
            name: dist
            target: /opt/giteeDownload/
            dependArtifact: DOCS
        script:
          - cd /opt/giteeDownload/
          - rm -rf dist
          - tar -zxvf dist.tar.gz
          - 'rm -rf /opt/docs/run/amap/* '
          - cp -r /opt/giteeDownload/dist/* /opt/docs/run/amap/
        strategy:
          retry: '0'
        dependsOn: build_nodejs
